name: Multi RDP with Proxy and Tailscale (10 Sessions)

on:
  workflow_dispatch:

jobs:
  rdp-proxy:
    runs-on: windows-latest
    timeout-minutes: 360
    strategy:
      matrix:
        proxy_index: [0,1,2,3,4,5,6,7,8,9]  # 10 parallel sessions using proxies.txt lines

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Safe read proxy from proxies.txt
      id: get_proxy
      shell: pwsh
      env:
        proxy_index: ${{ matrix.proxy_index }}
      run: |
        try {
          Write-Host "First 5 proxy lines:"
          Get-Content proxies.txt -TotalCount 5 | ForEach-Object { Write-Host $_ }

          $proxies = Get-Content proxies.txt
          $idx = [int]$env:proxy_index
          if ($idx -ge $proxies.Count) {
            throw "proxy_index $idx out of range; total proxies: $($proxies.Count)"
          }
          $line = $proxies[$idx].Trim()
          $split = $line -split "\s+"
          if ($split.Length -lt 2) {
            throw "Proxy line format invalid: $line"
          }
          $ipport = $split[0]
          $userpass = $split[1]
          echo "iproxy=$ipport" >> $env:GITHUB_OUTPUT
          echo "uproxy=$userpass" >> $env:GITHUB_OUTPUT
          Write-Host "Using proxy: $ipport with credentials $userpass"
        } catch {
          Write-Error $_.Exception.Message
          exit 1
        }

    - name: Set system proxy
      shell: pwsh
      run: |
        $ipport = "${{ steps.get_proxy.outputs.iproxy }}"
        $userpass = "${{ steps.get_proxy.outputs.uproxy }}"
        $proxyUri = "http://$userpass@$ipport"
        Write-Host "Setting http_proxy and https_proxy to $proxyUri"
        [Environment]::SetEnvironmentVariable('http_proxy', $proxyUri, [EnvironmentVariableTarget]::Machine)
        [Environment]::SetEnvironmentVariable('https_proxy', $proxyUri, [EnvironmentVariableTarget]::Machine)

    - name: Enable RDP & firewall rule
      shell: pwsh
      run: |
        Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Control\Terminal Server -Name fDenyTSConnections -Value 0 -Force
        netsh advfirewall firewall add rule name="RDP-Allow" dir=in action=allow protocol=TCP localport=3389

    - name: Create RDP user
      shell: pwsh
      run: |
        $password = 'TestPass123!'
        $securePass = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name 'rdpsession' -Password $securePass -AccountNeverExpires
        Add-LocalGroupMember -Group 'Remote Desktop Users' -Member 'rdpsession'
        Write-Host "User rdpsession created with password $password"

    - name: Install Tailscale
      shell: pwsh
      run: |
        $url = 'https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi'
        $file = "$env:TEMP\tailscale.msi"
        Invoke-WebRequest -Uri $url -OutFile $file
        Start-Process msiexec.exe -ArgumentList "/i `"$file`" /quiet /norestart" -Wait
        Remove-Item $file

    - name: Connect to Tailscale
      shell: pwsh
      env:
        proxy_index: ${{ matrix.proxy_index }}
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      run: |
        $hostName = "gh-runner-$env:proxy_index"
        Write-Host "Connecting Tailscale as $hostName"
        & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTH_KEY --hostname=$hostName
        $tsIP = $null
        $tries = 0
        while (-not $tsIP -and $tries -lt 20) {
          $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          Start-Sleep -Seconds 5
          $tries++
        }
        if (-not $tsIP) {
          Write-Error "Tailscale IP not assigned"
          exit 1
        }
        Write-Host "Tailscale IP: $tsIP"
        echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

    - name: Show session info
      shell: pwsh
      run: |
        Write-Host "Session $env:proxy_index Tailscale IP: $env:TAILSCALE_IP"
        Write-Host "RDP User: rdpsession"
        Write-Host "RDP Password: TestPass123!"

    - name: Keep runner alive
      shell: pwsh
      run: |
        while ($true) { Start-Sleep -Seconds 5 }
